In [1]:
import numpy as np
import pdb
from PIL import Image
from scipy import ndimage
import os
import unittest
from scipy.ndimage import maximum_filter
from numpy.lib.stride_tricks import as_strided

In [2]:
png_file = Image.open("C:\\Data\\2.png")
array_image = np.array(png_file)
kernel_3d = np.random.rand(3, 3, 4)
kernel_32d = np.random.rand(3, 3, 32)
png_file_1 = Image.open("C:\\Data\\1.png")
array_image_1 = np.array(png_file_1)
png_file_2 = Image.open("C:\\Data\\7.png")
array_image_2 = np.array(png_file_2)

In [77]:
array_image.shape

(590, 586, 4)

In [4]:
np.random.rand(2, 2)

array([[0.51571175, 0.71267851],
       [0.16118667, 0.86289568]])

In [5]:
array_image_1.shape

(343, 345, 4)

In [6]:
test = np.random.rand(294, 292, 32)

In [7]:
to_stack = []

In [139]:
t = np.array(create_kernels(64, 32))

In [140]:
t[0]

array([[[0.27095267, 0.27706946, 0.85321334, 0.04746348, 0.49127119,
         0.49528742, 0.2448475 , 0.63108959, 0.74947998, 0.57515579,
         0.86514623, 0.5277598 , 0.37217423, 0.34785694, 0.39083229,
         0.18979412, 0.06372974, 0.73091972, 0.52138576, 0.17315475,
         0.53310805, 0.88847276, 0.29904312, 0.29680763, 0.92435419,
         0.66835671, 0.98720611, 0.62452785, 0.37932148, 0.12373576,
         0.65239669, 0.70711151],
        [0.39258315, 0.88465091, 0.51643177, 0.71224922, 0.04102718,
         0.06798681, 0.85265685, 0.9405654 , 0.6868524 , 0.5909354 ,
         0.30714777, 0.74636423, 0.61023437, 0.24688906, 0.11239014,
         0.95555696, 0.3124456 , 0.00478241, 0.82395592, 0.59713757,
         0.94069933, 0.1178534 , 0.11134666, 0.15172482, 0.75724237,
         0.96490719, 0.61891541, 0.2258437 , 0.15228269, 0.61011504,
         0.68549969, 0.39096828],
        [0.69854141, 0.49117834, 0.85711063, 0.51454018, 0.66461443,
         0.03150035, 0.56964234, 0.

In [9]:
def reshape_dimensions_convolution(input_height, input_width, filter_height, filter_width, stride):
    output_height = int(((input_height - filter_height) / stride) + 1)
    output_width  = int(((input_width - filter_width)  / stride) + 1)
    return (output_height, output_width)

In [10]:
reshape_dimensions_convolution(3, 3, 2, 2, 1)

(2, 2)

In [11]:
def reshape_dimensions_pooling(input_height, input_width, f, s):
    output_height = int(((input_height - f) / s) + 1)
    output_width = int(((input_width - f) / s) + 1)
    return (output_height, output_width)

In [141]:
def forward_pass(image):
    shape = image.shape
    kernels = create_kernels(32, 4)
    kernels2 =  create_kernels(64, 32)
    pdb.set_trace()
    to_stack_values = []
    dimensions = reshape_dimensions_convolution(shape[0], shape[1], 3, 3, 1) 
    for i in range(len(kernels)):
        to_stack_values.append(convolve_one_step_vectorized(image, kernels[i]))
    stacked_filters = np.stack(to_stack_values, axis = 2)
    first_ReLU = ReLUv2(stacked_filters)
    pool_to_reshape = reshape_dimensions_pooling(first_ReLU.shape[0], first_ReLU.shape[1], 2, 2)
    first_max_pool = np.array(max_pooling(first_ReLU)).reshape(pool_to_reshape[0], pool_to_reshape[1], 32)
    to_stack_values.clear()
    shape2 = first_max_pool.shape
    return shape2
    for f in range(len(kernels2)):
        to_stack_values.append(convolve_one_step_vectorized(first_max_pool, kernels2[f]))
    return to_stack_values
    
    """
    stacked_filters2 = np.stack(to_stack_values, axis = 2)
    second_ReLU = np.array(ReLUv2(stacked_filters2))
    pool_to_reshape2 = reshape_dimensions_pooling(second_ReLU.shape[0], second_ReLU.shape[1], 2, 2)
    second_max_pool = np.array(max_pooling(second_ReLU).reshape(pool_to_reshape[2], pool_to_reshape[2]), 64)
    return second_max_pool
    """

In [ ]:
forward_pass(array_image)

> c:\users\dembek\appdata\local\temp\ipykernel_14576\2001528463.py(6)forward_pass()



In [14]:
shajp = test.shape

In [15]:
to_reshape = reshape_dimensions_convolution(shajp[0], shajp[1], 3, 3, 1)

In [16]:
alfa.shape

NameError: name 'alfa' is not defined

In [135]:
def create_kernels(number_to_create, depth):
    every_kernel = []
    for f_u in range(number_to_create):
        every_kernel.append(np.random.rand(3, 3, depth))
    return np.array(every_kernel)

In [17]:
test_image = np.random.rand(10, 10, 4)

In [18]:
def convolve_one_step(input_image, kernel_used):
    intermediate_values = []
    dimensions = input_image.shape
    dimensions_kernel = kernel_used.shape
    final_values = []
    dimensions_to_reshape = reshape_dimensions_convolution(dimensions[0], dimensions[1], dimensions_kernel[0], dimensions_kernel[1], 1)
    for i in range(dimensions[0] - 2):
        for j in range(dimensions[1] - 2):
            for k in range(dimensions[2] ):
                slice_of_image = input_image[i : i + 3, j : j + 3, k]
                real_kernel = kernel_used[:, :, k]
                value = np.vdot(slice_of_image, real_kernel)
                intermediate_values.append(value)
                #pdb.set_trace()
                if len(intermediate_values) == dimensions[2]:
                    final_values.append(sum_dimension(intermediate_values))
                    intermediate_values.clear()
                    
    return np.array(final_values).reshape(dimensions_to_reshape)

In [19]:
def sum_dimension(list_of_three):
    return sum(list_of_three)

In [20]:
image_after_conv_2 = np.array(convolve_one_step(array_image, kernel_3d)).reshape(dimensions[0], dimensions[1], 1)

NameError: name 'dimensions' is not defined

In [29]:
def max_pooling(image_array):
    pooling_values = []
    for m in range(0, image_array.shape[0], 2):
        for n in range(0, image_array.shape[1], 2):
            for o in range(image_array.shape[2]):
                if n + 2 > image_array.shape[1]:
                    slice_of_pooling = image_array[m : m + 2, n - 1: n + 1 , o]
                else:
                    slice_of_pooling = image_array[m : m + 2, n : n + 2 , o]
                pooling_values.append(slice_of_pooling.max())
                #pdb.set_trace()
    return pooling_values

In [30]:
filtr = test_image[0 : 2, 0 : 2, 0]

In [31]:
after_maxpool = np.array(max_pooling(test_image)).reshape(5, 5, 4)

In [32]:
after_maxpool.shape

(5, 5, 4)

In [33]:
def ReLUv1(x):
    after_relu = []
    for r in x:
        if r > 0:
            after_relu.append(r)
        else:
            after_relu.append(0)
    return after_relu

In [34]:
def ReLUv2(x):
    return np.maximum(0, x)

In [35]:
last_pool = np.random.rand(2, 2, 1)

In [36]:
def fully_connected(after_last_max_pool, number_of_nodes):
    almost_values = []
    nodes_values = []
    flatten_array = after_last_max_pool.reshape(4)
    weights = np.random.rand(len(flatten_array), number_of_nodes)
    for x in range(weights.shape[1]):
        for y in range(weights.shape[0]):
            if y == weights.shape[0] - 1:
                almost_values.append(weights[y : y + 1, x] * flatten_array[y])
                nodes_values.append(sum(almost_values))
                almost_values.clear()
            else:
                almost_values.append(weights[y : y + 1, x] * flatten_array[y])
    return nodes_values

In [37]:
fully_connected(last_pool, 4)

[array([1.14327827]),
 array([1.01122261]),
 array([0.91411365]),
 array([0.86652043])]

In [78]:
test_image = np.random.rand(10, 10, 4)

In [39]:
test_kernel = np.random.rand(3, 3, 4)

In [40]:
def reshape_to_matrix_image(height, width, kernel_height, kernel_width, depth):
    number_of_patches = np.prod(reshape_dimensions_convolution(height, width, kernel_height, kernel_width, 1))
    each_patch_size = kernel_height * kernel_width * depth
    return (number_of_patches, each_patch_size)

In [41]:
reshape_to_matrix_image(7, 7, 3, 3, 4)

(25, 36)

In [71]:
def convolve_one_step_vectorized(imput_image, kernel_used):
    shape_of_image = imput_image.shape
    kernel_used_shape = kernel_used.shape
    dim_to_reshape = reshape_dimensions_convolution(shape_of_image[0], shape_of_image[1], kernel_used_shape[0], kernel_used_shape[1], 1)
    reshaped_image  = reshape_to_matrix_valid(imput_image, (3, 3), 1, -1, 36)
    reshaped_kernel = np.squeeze(reshape_to_matrix_valid(kernel_used, (3, 3), 1, -1, 1))
    #pdb.set_trace()
    vectorized_output = np.matmul(reshaped_image, reshaped_kernel)
    return vectorized_output.reshape(dim_to_reshape)

In [79]:
def reshape_to_matrix_valid(image, patch_size, stride, rA, rB):
    shape = (image.shape[0] - patch_size[0] + 1,
             image.shape[1] - patch_size[1] + 1,
             patch_size[0],
             patch_size[1],
             image.shape[2])
    #pdb.set_trace()
    strides = (image.strides[0],
               image.strides[1],
               image.strides[0],
               image.strides[1],
               image.strides[2])
    patches = as_strided(image, shape, strides)
    #reshaped_patches = patches.reshape(rA, rB)
    return patches.reshape(rA, rB)

In [49]:
reshape_to_matrix_valid(array_image, (3, 3), 1, 9, -1)

(9, 1373568)

In [75]:
reshape_dimensions_convolution(5, 5, 3, 3, 1)

(3, 3)

In [87]:
a = convolve_one_step_vectorized(array_image, test_kernel)

In [89]:
b = convolve_one_step(array_image, test_kernel)

In [90]:
a == b

array([[ True,  True,  True, ...,  True,  True,  True],
       [ True,  True,  True, ...,  True,  True,  True],
       [ True,  True,  True, ...,  True,  True,  True],
       ...,
       [ True,  True,  True, ...,  True,  True,  True],
       [ True,  True,  True, ...,  True,  True,  True],
       [ True,  True,  True, ...,  True,  True,  True]])

In [120]:
test = np.random.rand(294, 292, 32)

In [123]:
reshape_to_matrix_valid(test, (3, 3), 1, -1, 36)

array([[0.40892837, 0.98406771, 0.9291834 , ..., 0.85679094, 0.74733506,
        0.95310039],
       [0.83176372, 0.99945566, 0.56495447, ..., 0.81440245, 0.14831733,
        0.18372342],
       [0.60038196, 0.55074676, 0.72877485, ..., 0.15020271, 0.17161545,
        0.60488458],
       ...,
       [0.35734984, 0.42391069, 0.88067068, ..., 0.92736611, 0.91783363,
        0.94606488],
       [0.30460019, 0.99665277, 0.96139911, ..., 0.10236035, 0.98055949,
        0.97953185],
       [0.55694384, 0.34237612, 0.0682504 , ..., 0.40025369, 0.43285598,
        0.60214601]])